export const REMOVE_FROM_LOCAL_STORAGE = 'REMOVE_FROM_LOCAL_STORAGE';
export const ADD_TO_LOCAL_STORAGE = 'ADD_TO_LOCAL_STORAGE';
export const LOCAL_STORAGE_READ = 'LOCAL_STORAGE_READ';
export const LOCAL_STORAGE_CLEAR = 'LOCAL_STORAGE_CLEAR';
export const LOCAL_STORAGE =  'BASKET';
