export const ADD_TO_BASKET_REQUEST = 'ADD_TO_BASKET_REQUEST';
export const ADD_TO_BASKET_ERROR = 'ADD_TO_BASKET_ERROR';
export const ADD_TO_BASKET_SUCCESS = 'ADD_TO_BASKET_SUCCESS';
export const DELETE_FROM_BASKET_REQUEST = 'DELETE_FROM_BASKET_REQUEST';
export const DELETE_FROM_BASKET_ERROR = 'DELETE_FROM_BASKET_ERROR';
export const DELETE_FROM_BASKET_SUCCESS = 'DELETE_FROM_BASKET_SUCCESS';

