export const ADD_TO_BASKET_REQUEST = 'ADD_TO_BASKET_REQUEST';
export const ADD_TO_BASKET_ERROR = 'ADD_TO_BASKET_ERROR';
export const ADD_TO_BASKET_SUCCESS = 'ADD_TO_BASKET_SUCCESS';
export const REM_FROM_BASKET_REQUEST = 'REM_FROM_BASKET_REQUEST';
export const REM_FROM_BASKET_ERROR = 'REM_FROM_BASKET_ERROR';
export const REM_FROM_BASKET_SUCCESS = 'REM_FROM_BASKET_SUCCESS';

